### ISSUE TITLE
Don't fix teams during dry run time 

### ISSUE THREAD

**Issue by HumairAK** [operate-first/common#63]
When adding new teams we see ci failures: https://github.com/operate-first/common/pull/62 

This is probably due to https://github.com/operate-first/common/blob/ca7c1f05d85cbe14cd52fbacc55768989c68ef82/.prow.yaml#L36
which we shouldn't be doing during a dry run.

**Comment by durandom** [comment]
@HumairAK @harshad16 do you want to keep #62 open for debugging?

**Comment by harshad16** [comment]
no, we will open a separate pr to fix this.

**Comment by Gregory-Pereira** [comment]
@HumairAK  has this been anymore cases involving this? I found [this issue in peribolos](https://github.com/kubernetes/test-infra/issues/26542) which seems to be related, however seeing as I can't check the logs for the failed test I cant verify. Weather this is due to the `ci-prow` bucket overflowing OBCs incedent or simply because the logs have expired I am getting a 504. I am happy to make this change regardless in a PR I just want to see if you have seen any examples of this since, or if this issue has not reoccured yet.
/remove-lifecycle stale

**Comment by HumairAK** [comment]
@Gregory-Pereira an easy way to tell would be to emulate a test pr where a team is being added and see if the ci fails
